# Generated by Django 2.2.7 on 2019-11-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
        ('seller_app', '0002_spdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpGurantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gurantee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100000, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('minimum_qty', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.SpDivision')),
                ('guarantee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.SpGurantee')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.SpSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SpProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.SpProduct')),
            ],
        ),
    ]
