# Generated by Django 2.2.7 on 2019-11-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_app', '0002_spdivision'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=255)),
                ('longtitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('ship_charge', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.ScUser')),
            ],
        ),
        migrations.CreateModel(
            name='SpOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('qty', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.SpOrder')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.SpProduct')),
            ],
        ),
    ]
