# Generated by Django 2.2.7 on 2019-11-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
                ('minimum_qty', models.IntegerField()),
            ],
        ),
    ]
