# Generated by Django 2.2.7 on 2019-11-11 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
        ('seller_app', '0002_spdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='WbCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('salt', models.IntegerField()),
                ('pp_no', models.CharField(max_length=20)),
                ('nid_no', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.ScUser')),
            ],
        ),
        migrations.CreateModel(
            name='SpPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pay_status', models.IntegerField()),
                ('delivery_status', models.IntegerField()),
                ('user_status', models.IntegerField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_app.WbCard')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.SpOrder')),
            ],
        ),
    ]
