# Generated by Django 2.2.7 on 2019-11-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_app', '0001_initial'),
        ('seller_app', '0002_spdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpDeliveryBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=255)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.SpSeller')),
            ],
        ),
        migrations.CreateModel(
            name='SpDeliveryOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=255)),
                ('long_start', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lat_start', models.DecimalField(decimal_places=3, max_digits=10)),
                ('long_end', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lat_end', models.DecimalField(decimal_places=3, max_digits=10)),
                ('delivery_boy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.SpDeliveryBoy')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_app.SpPurchase')),
            ],
        ),
    ]
